[package]
name = "drill-mobile-viewer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
drill-core = { path = "../drill-core", version = "0.1.0" }
drill-render = { path = "../drill-render", version = "0.1.0" }

[dev-dependencies]
blake3 = "1.8.6"

[[bench]]
name = "generation_performance"
harness = false
